### PR TITLE
fixed DC-4033 ZTB - Filters not working

### PR DESCRIPTION
**Pull request by hiteshzuru**

### CODE REVIEW

**Comment by Dipen-Dedania** [comment]
`minSliderValue.setMinutes(minSliderValue.getMinutes() + 330);`

@hiteshzuru What's the purpose behind this 330 static value?

**Comment by hiteshzuru** [comment]
@Dipen-Dedania 
There was one issue in slider click. Mainly at the ends of the slider.
It was also getting the time of the point where it was clicked.  That is the slider's behavior.
And in our system, the blogs were displayed if the date matched & the time matched to ``05:30:00 GMT+0530 (India Standard Time)``.

While we are not displaying the time in the slider & just dealing with the date, we have to shoe all the matched blogs when that matched date displayed in the slider.

So, first of all, I get the date by ``formatDateString(ui.values[0])`` which gives the date with ``00:00:00 GMT+0530 (India Standard Time)``.
So I added 5 hours & 30 minutes (330 minutes) in this & that fixed the issue and we got the blogs as per our requirement.

**Comment by Dipen-Dedania** [comment]
@hiteshzuru User will be from different time zone, not just from IST only. Make sure to cover all the scenarios.

**Comment by hiteshzuru** [comment]
@Dipen-Dedania,
I thought it will not affect that but it was affected.
I have fixed this issue and also make PR for this: https://github.com/zurutech/zurutech.github.io/pull/23

**Pull request closed without merging**
