### PR TITLE
Fix : Modify footer according to website

### PR DESCRIPTION
**Pull request by karanparmar1**
fix : Blog: Modify footer according to website

-updates blog footer with zuru.tech footer
-passes query parameter preference=true when user  clicks Do not Sell my Personal Information from blog footer

Fixes OS-1708

### CODE REVIEW

**Comment by Dipen-Dedania** [comment]
@karanparmar1 Can you please add a preview link of these changes?

**Comment by galeone** [comment]
why removing the "Careers" section in the footer?

**Comment by Harshmakadia** [comment]
@galeone - In order to make it consistent with the footer of our site https://zuru.tech/ 

Right now https://blog.zuru.tech/ has different footer compared to  https://zuru.tech/

**Comment by galeone** [comment]
got it, thanks!

**Pull request merged**
